home/urls.py
from django.urls import path, include

from home.views import HomeView, ProductDetailView, BucketView, BucketDeleteObjectView, BucketDownloadObjectView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'
bucket_urls = [
    path('', BucketView.as_view(), name='bucket'),
    path('delete_obj/<str:key>/', BucketDeleteObjectView .as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>/', BucketDownloadObjectView .as_view(), name='download_obj_bucket'),

]


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product-detail'),
    path('category/<slug:category_slug>/', HomeView.as_view(), name='category_filter'),
]

orders/urls.py
from django.urls import path

from orders.views import CartView, CartAddView, CartRemoveView, CreateOderView, OrderDetailView, OrderPayView, \
    OrderVerifyView, CouponApplyView

app_name = 'order'
urlpatterns = [
    path('create/', CreateOderView.as_view(), name='order_create'),
    path('detail/<int:order_id>', OrderDetailView.as_view(), name='order_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>', CartAddView.as_view(), name='cart'),
    path('cart/remove/<int:product_id>', CartRemoveView.as_view(), name='remove'),
    path('pay/<int:order_id>/', OrderPayView.as_view(), name='order_pay'),
    path('verify/', OrderVerifyView.as_view(), name='order_verify'),
    path('apply/<int:order_id>/', CouponApplyView.as_view(), name='apply_coupon'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
]

home/models.py
from django.db import models
from   django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, unique=True)
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='subCategory')
    is_sub = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ('name',)

    def __str__(self):
        return f'{self.name} -> {self.slug}'

    def get_absolute_url(self):
        return reverse('home:category_filter', args=[self.slug])

class Product(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, unique=True)
    category = models.ManyToManyField(Category, related_name='products')
    price = models.BigIntegerField()
    image = models.ImageField()
    description = models.TextField()
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('home:product-detail', args=[self.slug])

    def __str__(self):
        return f'{self.name}'

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Product, Category
from . import tasks
from django.contrib import messages
from utils import UserIsAdmin

from orders.forms import CartAddForm


class HomeView(View):
    def get(self, request, category_slug=None):
        products = Product.objects.filter(available=True)
        categories = Category.objects.filter(is_sub=False)
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            products = products.filter(category=category)

        return render(request, 'home/home.html', {'products': products, 'categories': categories})


class ProductDetailView(View):
    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        form = CartAddForm()
        return render(request, 'home/detail.html', {'product': product, 'form': form})


class BucketView(UserIsAdmin, View):
    template_name = 'home/bucket.html'

    def get(self, request):
        # res = all_buckets_objects_task.delay()
        res = tasks.all_buckets_objects_task()
        print('=' * 20)
        print(res)

        return render(request, self.template_name, {'objects': res})


class BucketDeleteObjectView(UserIsAdmin, View):
    def get(self, request, key):
        tasks.delete_object_ask.delay(key)
        messages.success(request, 'Your image delete successfully', 'info')
        return redirect('home:bucket')


class BucketDownloadObjectView(UserIsAdmin, View):

    def get(self, request, key):
        tasks.download_object_task.delay(key)
        messages.success(request, 'Your image Download successfully', 'info')
        return redirect('home:bucket')

home/templates/home/bucket.html
{% extends 'base.html' %}


{% block title %}
bucket
{%endblock%}

{% block content %}
<table class="table dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">name</th>
      <th scope="col">size</th>
      <th scope="col">download</th>
      <th scope="col">delete</th>
    </tr>
  </thead>
  <tbody>
  {% for obj in objects %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{obj.Key}}</td>
      <td>{{obj.Size | filesizeformat}}</td>
      <td>
        <a href="{% url 'home:download_obj_bucket' obj.Key %}">
        @download
        </a>
      </td>
      <td>
        <a href="{% url 'home:delete_obj_bucket' obj.Key %}">Delete</a>
      </td>
    </tr>
  {% endfor %}

  </tbody>
</table>
{%endblock%}

home/templates/home/detail.html
{% extends 'base.html' %}


{% block title %}
Product {{product.name }}
{%endblock%}

{% block content %}
<h2>
    {{product.name}}
</h2>
<small>{{product.created_at}}</small><br>
<p>{{product.price}}</p>
<p>
{% for cat in product.category.all %}
<h5 style="display:inline-block">{{cat.name}} | </h5>
{% endfor %}
</p>
<img src="{{product.image.url}}" alt="">
<p>{{product.description}}</p>
<p>
<form action="{% url 'order:cart' product.id %}" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="add to cart">
</form>
</p>


{%endblock%}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block extra_headers %}
<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock %}

{% block title %}
Home
{%endblock%}

{% block content %}
<h3>
    {% if request.user.is_authenticated %}
        Hello User
    {% else %}
        Hello world
{% endif %}
    </h3>
<div class="row">
    <div class="col-sm-12">
        <div class="btn-group">
              <button type="button" class="btn btn-danger"><a href="{% url 'home:home' %}" >All</a></button>
             {% for category in categories %}
            <button type="button" class="btn btn-danger"> <a href="{{ category.get_absolute_url }}" >{{category.name}}</a></button>
              <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu">
                  {% for sub in category.subCategory.all %}
                <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{sub.name}}</a></li>
                   {% endfor %}
              </ul>
            {% endfor %}
        </div>
        </div>
</div>



<div class="row">
{% for product in products %}
       <div class="card col-lg-12" style="width: 18rem; margin:5px;">
          <img src='{{ product.image.url }}' class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">{{product.name}}</h5>
            <p class="card-text">{{product.description}}</p>
            <a href="{{product.get_absolute_url}}" class="btn btn-primary">Go details</a>
          </div>
    </div>
{% endfor %}
    </div>
{%endblock%}