accounts/urls.py
from django.urls import path
from accounts.views import UserRegisterView, UserVerifyCode, UserLoginView, UserLogoutView

app_name = 'accounts'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user_register'),
    path('verify_code/', UserVerifyCode.as_view(), name='verify_code'),
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
]

home/urls.py
from django.urls import path, include

from home.views import HomeView, ProductDetailView, BucketView, BucketDeleteObjectView, BucketDownloadObjectView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'
bucket_urls = [
    path('', BucketView.as_view(), name='bucket'),
    path('delete_obj/<str:key>/', BucketDeleteObjectView .as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>/', BucketDownloadObjectView .as_view(), name='download_obj_bucket'),

]


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product-detail'),
    path('category/<slug:category_slug>/', HomeView.as_view(), name='category_filter'),
]

orders/urls.py
from django.urls import path

from orders.views import CartView, CartAddView, CartRemoveView, CreateOderView, OrderDetailView, OrderPayView, \
    OrderVerifyView, CouponApplyView

app_name = 'order'
urlpatterns = [
    path('create/', CreateOderView.as_view(), name='order_create'),
    path('detail/<int:order_id>', OrderDetailView.as_view(), name='order_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>', CartAddView.as_view(), name='cart'),
    path('cart/remove/<int:product_id>', CartRemoveView.as_view(), name='remove'),
    path('pay/<int:order_id>/', OrderPayView.as_view(), name='order_pay'),
    path('verify/', OrderVerifyView.as_view(), name='order_verify'),
    path('apply/<int:order_id>/', CouponApplyView.as_view(), name='apply_coupon'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
]

templates/inc/messages.html
{%if messages%}
    {% for msg in messages%}
        <p class="alert alert-{{msg.tags}}"> {{msg}} </p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>
        {% if request.user.is_authenticated %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:user_logout' %}">logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:user_register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:user_login' %}">Login</a>
        </li>
        {% endif %}
        {% if request.user.is_admin %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:bucket' %}">BuCket</a>
        </li>
        {% endif %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'order:cart' %}">Cart {{ cart|length }}</a>
        </li>
      </ul>
    </div>
  </div>
</nav>